[package]
name = "bridge-message-executor"
version = "0.1.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
chrono = "0.4.22"
fuel-core-interfaces = "0.14"
fuels = { version = "0.30", features = ["fuel-core-lib"] }
futures = "0.3.25"
